### ISSUE TITLE
Submodule issue in extern folder. 

### ISSUE THREAD

**Issue by DanThomas64** [SQFvm/language-server#17]
https://github.com/SQFvm/language-server/tree/master/server/extern

VM is a dead link.  I assume that this is meant to point at the SQFvm runtime?

**Comment by X39** [comment]
Damn you CLion 🫠

Yes, it should refer to the VM but apparently a commit is still on my local computer, thanks for the headsup. Will fix ASAP

**Comment by X39** [comment]
Done
