### ISSUE TITLE
[BUG] Max Numbers Of Problems setting not working

### ISSUE THREAD

**Issue by MildlyInterested** [SQFvm/language-server#18]
**Describe the bug**
sqfVmLanguageServer.maxNumberOfProblems set to 100 but displaying 362 Problems.

**To Reproduce**
1. Go to extension settings and confirm max problems is set to 100
2. Copy this repo with plenty of errors: https://github.com/16AA-Milsim/MissionFramework
3. 300+ Problems reported

**Expected behavior**
Only show the first? 100 Problems

**Comment by X39** [comment]
The option used to be implemented as a countermeasure for extremly large projects, as indexing used to have to be done on every launch. That is a thing of the past and implementing that limit probably is much more work then just fully removing it.

Are there any issues happening with that many problems being reported? if yes, which one are they?

**Comment by MildlyInterested** [comment]
I assumed it was supposed to be working that's why I reported it. Your explanation makes sense so in my opinion removing it is the best option.

**Comment by X39** [comment]
removed
