### ISSUE TITLE
[BUG] Deleting file does not update cached problems

### ISSUE THREAD

**Issue by MildlyInterested** [SQFvm/language-server#21]
Deleting a file or switching branches does not seem to update the cached problems and shows outdated issues in "ghost files" or "ghost lines".
1. Open attached zip in VSCode
2. See three errors
3. Delete sample.sqf
4. Still reports three problems

Same happens if you switch branches, e.g. in this repo https://github.com/16AA-Milsim/MissionFramework switching from master to feature/function_rewrite still reports errors in `initServer.sqf`.

[test.zip](https://github.com/SQFvm/language-server/files/12322153/test.zip)

**Comment by X39** [comment]
fixed

**Comment by MildlyInterested** [comment]
not quite, see #28
