### ISSUE TITLE
[BUG] Copying folder into workspace does not trigger rescan

### ISSUE THREAD

**Issue by MildlyInterested** [SQFvm/language-server#28]
1. Download both zip files
2. open test.zip in VSCode
3. copy in the taw_vd folder
4. Does not flag issues in new files

[taw_vd.zip](https://github.com/SQFvm/language-server/files/12326992/taw_vd.zip)
[test.zip](https://github.com/SQFvm/language-server/files/12326993/test.zip)

Same goes for deleting a whole folder, SQFvm does not update the problems list.

**Comment by X39** [comment]
fixed in https://github.com/SQFvm/language-server/commit/ee92e52499a053b8d65caea1723c5210d4280fb9
