### ISSUE TITLE
Round brackets misc

### ISSUE THREAD

**Issue by MildlyInterested** [SQFvm/language-server#45]
In `fn_opensavemanager.sqf` line 26 and 29 I believe the round brackets are neccessary. 
![image](https://github.com/SQFvm/language-server/assets/57712666/79fe2508-666c-45d1-a98c-876f128b52a2)

In `fn_openmenu.sqf` line 14 I believe the round brackets are neccessary.
![image](https://github.com/SQFvm/language-server/assets/57712666/0bfdf60e-4cfa-48ab-9d6b-b44786440b37)

In `fn_onsaveselectionchanged.sqf` line 18 the lines are in the wrong spot.
![image](https://github.com/SQFvm/language-server/assets/57712666/74e67577-6928-4a86-ab35-9d8f42e1cf69)
 
[taw_vd.zip](https://github.com/SQFvm/language-server/files/12378156/taw_vd.zip)

**Comment by X39** [comment]
For macros, the safety messages pretty much can be ignored (for the most part, they are a result of the rather pitty of doing macro stuff "safe")

However, all of those hints are correct
