### ISSUE TITLE
Configure path mapping via settings or project files

### ISSUE THREAD

**Issue by veteran29** [SQFvm/language-server#48]
It would be useful to allow mapping virtual paths via setting like in vscode-sqflint:
```json
    "sqflint.includePrefixes": {
        "\\a3\\": "P:/a3/",
        "\\vn\\": "P:/vn/",
    },
```

Project level configuration wile with support for VSCode variables like:
`${fileWorkspaceFolder}` etc. could also be useful.
https://code.visualstudio.com/docs/editor/variables-reference

**Comment by X39** [comment]
implemented in 394c001514253d92dbfc64cb47fd4d3a74746efc

Actual configuration layout is slightly different, using explicit naming instead of implicit key-value list
